
public class Sabonete {
	//ATRIBUTOS DO SABONETE
	String cheiro;
	String cor;

	//CONSTRUTOR DA CLASSE SABOENTE
	public Sabonete(String cheiro, String cor) {
		this.cheiro = cheiro;
		this.cor = cor;
	}
	
	//SOBRECARGA DO CONTRUTOR DO SABONETE, NESSE CASO RECEBENDO UMA UNICA STRING

	public Sabonete(String linha) {
		//ESSE CONSTRUTOR E RESPONSAVEL POR PEGAR A STRING EM FORMATO DE TOSTRING E RETORNAR ELA PARA O ESTADO DE OBJETO
		//NOS PEGAMOS OS VALORES QUEBRANDO A STRING EM LUGARES ESPECIFICOS
		//COMO POR EXEMPLO NA VIRGULA
		String[] ArrayTeste1 = linha.split(",");
		//DEPOIS QUE QUEBRAMOS A STRING NA VIRGULA TEMOS DUAS STRING DENTRO DA ARRAYTESTE1
		//DESSA FORMA QUANDO PEGAMOS O VALOR NA POSICAO 0, ESTAMOS PEGANDO A PRIMEIRA PARTE DA STRING QUEBRADA
		//OU SEJA "SABONETE: CHEIRO="
		String[] ArrayTeste2 = ArrayTeste1[0].split("=");
		//AO PEGAR ESSA PARTE DA STRING NOS QUEBRAMOS ELA DE NOVO NO SINAL DE IGUAL
		//E ARMAZENAMOS EM ARRAYTESTE2

		//FINALIZAMOS TIRANDO OS ESPACOS VAZIOS DAS PONTAS COM .TRIM()
		//E COLOCAMOS O SEU VALOR NO ATRIBUTO CHEIRO
		//COMO O ATRIBUTO CHEIRO TAMBEM E UMA STRING NAO PRECISAMOS FAZER NENHUM CASTING
		this.cheiro = ArrayTeste2[1].trim();
		
		//REALIZAMOS O MESMO PROCEDIMENTO, MAS AGORA COM A SEGUNDA PARTE DA STRING
		String[] ArrayTeste3 = ArrayTeste1[1].split("=");
		//E DEPOIS DE SEPARAR O SEU VALOR ARMAZENAMOS ELE NO ATRIBUTO DO SABONETE
		this.cor = ArrayTeste3[1].trim();
	}


	@Override
	public String toString() {
		return "Sabonete: Cheiro=" + cheiro + ", Cor=" + cor;
	}

	
}
